# Generated by Django 3.1.5 on 2021-01-24 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_device_usage', models.IntegerField(blank=True, null=True)),
                ('device_name', models.CharField(max_length=255)),
                ('expenses', models.FloatField()),
                ('revenue', models.FloatField(default=0)),
                ('mining_rate', models.IntegerField()),
                ('power_consumption', models.IntegerField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_list',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='PowerCost',
            fields=[
                ('power_cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_per_watH', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'power_cost',
            },
        ),
        migrations.CreateModel(
            name='DeviceUsage',
            fields=[
                ('device_usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.device')),
            ],
            options={
                'db_table': 'device_usage',
            },
        ),
    ]
